version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing Git.."  
      - sudo apt update
      - sudo apt install git
      - git clone -b develop https://${Token}@github.com/nakulgrover18/github-testing.git
      
      
artifacts:
  files:
    - '**/*'      